### ISSUE TITLE
Add Optional functions

### ISSUE THREAD

**Issue by quintok** [messagemedia/mm-jackson-support#1]
Hello,

What do you think as treating this as a special case of Optional?

if so, add functions like: filter, flatmap, map, ifPresent, stream etc.

**Comment by elruwen** [comment]
I initially was hoping to have one constant for ABSENT and for EXPLICT_NULL. That didn't work. In that case I would have provided all the Optional-style methods.

Generally I would expect that people handle the explicit null like they would handle a value. For example:

````
public class JsonObject {
private ValueWithNull<String> mystring;
....
}

// transfer data/explicit delete (null) into db pojo if present
Optional.ofNullable(jsonObject.getMystring().ifPresent(x-> mydbpojo.setMystring(x));
````

So basically you want something like this:

````
public class JsonObject {
private ValueWithNull<String> mystring;
....
}

// transfer data/explicit delete (null) into db pojo if present
Optional.ofNullable(jsonObject.getMystring().ifPresent(x-> mydbpojo.ifPresent(y -> dosomething).orElse(dosomethingelse));
````

I find it awkward to do something else will and explicit null then with a value. And the above code looks weird to me. Do you have an example for such a case?

**Comment by quintok** [comment]
Doesn't have to be so heavy, could even change the `get` method to Optional<T> may be more efficient use of your time.

Saves you having to re-implement the methods.

**Comment by elruwen** [comment]
Returning an Optional sounds like a good idea ;)
